/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UndeployedPreflightRouteImport } from './routes/undeployed-preflight'
import { Route as UndeployedRouteImport } from './routes/undeployed'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as QuantumPrimerRouteImport } from './routes/quantum-primer'
import { Route as ProofServerRouteImport } from './routes/proof-server'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LlmsRouteImport } from './routes/llms'
import { Route as KnownIssuesRouteImport } from './routes/known-issues'
import { Route as IdentusRouteImport } from './routes/identus'
import { Route as AgenticExperimentalRouteImport } from './routes/agentic-experimental'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ThemesThemeRouteImport } from './routes/themes.$theme'
import { Route as ShowcaseX402MidnightPaywallRouteImport } from './routes/showcase.x402-midnight-paywall'
import { Route as ShowcaseUcpZkCheckoutRouteImport } from './routes/showcase.ucp-zk-checkout'
import { Route as ShowcaseProgrammaticDustRouteImport } from './routes/showcase.programmatic-dust'
import { Route as ShowcaseMoveBoardRouteImport } from './routes/showcase.move-board'
import { Route as ShowcaseMidnightLedgerRouteImport } from './routes/showcase.midnight-ledger'
import { Route as ShowcaseChoreoLedgerLocalRouteImport } from './routes/showcase.choreo-ledger-local'
import { Route as ShowcaseA2aAp2NegotiationRouteImport } from './routes/showcase.a2a-ap2-negotiation'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicX402ProxyRouteImport } from './routes/api/public/x402-proxy'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UndeployedPreflightRoute = UndeployedPreflightRouteImport.update({
  id: '/undeployed-preflight',
  path: '/undeployed-preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const UndeployedRoute = UndeployedRouteImport.update({
  id: '/undeployed',
  path: '/undeployed',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumPrimerRoute = QuantumPrimerRouteImport.update({
  id: '/quantum-primer',
  path: '/quantum-primer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofServerRoute = ProofServerRouteImport.update({
  id: '/proof-server',
  path: '/proof-server',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsRoute = LlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const KnownIssuesRoute = KnownIssuesRouteImport.update({
  id: '/known-issues',
  path: '/known-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentusRoute = IdentusRouteImport.update({
  id: '/identus',
  path: '/identus',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticExperimentalRoute = AgenticExperimentalRouteImport.update({
  id: '/agentic-experimental',
  path: '/agentic-experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesThemeRoute = ThemesThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseX402MidnightPaywallRoute =
  ShowcaseX402MidnightPaywallRouteImport.update({
    id: '/x402-midnight-paywall',
    path: '/x402-midnight-paywall',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const ShowcaseUcpZkCheckoutRoute = ShowcaseUcpZkCheckoutRouteImport.update({
  id: '/ucp-zk-checkout',
  path: '/ucp-zk-checkout',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseProgrammaticDustRoute =
  ShowcaseProgrammaticDustRouteImport.update({
    id: '/programmatic-dust',
    path: '/programmatic-dust',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const ShowcaseMoveBoardRoute = ShowcaseMoveBoardRouteImport.update({
  id: '/move-board',
  path: '/move-board',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseMidnightLedgerRoute = ShowcaseMidnightLedgerRouteImport.update({
  id: '/midnight-ledger',
  path: '/midnight-ledger',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseChoreoLedgerLocalRoute =
  ShowcaseChoreoLedgerLocalRouteImport.update({
    id: '/choreo-ledger-local',
    path: '/choreo-ledger-local',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const ShowcaseA2aAp2NegotiationRoute =
  ShowcaseA2aAp2NegotiationRouteImport.update({
    id: '/a2a-ap2-negotiation',
    path: '/a2a-ap2-negotiation',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402ProxyRoute = ApiPublicX402ProxyRouteImport.update({
  id: '/api/public/x402-proxy',
  path: '/api/public/x402-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/identus': typeof IdentusRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/mobile': typeof MobileRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/a2a-ap2-negotiation': typeof ShowcaseA2aAp2NegotiationRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/showcase/ucp-zk-checkout': typeof ShowcaseUcpZkCheckoutRoute
  '/showcase/x402-midnight-paywall': typeof ShowcaseX402MidnightPaywallRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/blog/': typeof BlogIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/identus': typeof IdentusRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/mobile': typeof MobileRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/strategy': typeof StrategyRoute
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/a2a-ap2-negotiation': typeof ShowcaseA2aAp2NegotiationRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/showcase/ucp-zk-checkout': typeof ShowcaseUcpZkCheckoutRoute
  '/showcase/x402-midnight-paywall': typeof ShowcaseX402MidnightPaywallRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/blog': typeof BlogIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-experimental': typeof AgenticExperimentalRoute
  '/identus': typeof IdentusRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/mobile': typeof MobileRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/a2a-ap2-negotiation': typeof ShowcaseA2aAp2NegotiationRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/showcase/ucp-zk-checkout': typeof ShowcaseUcpZkCheckoutRoute
  '/showcase/x402-midnight-paywall': typeof ShowcaseX402MidnightPaywallRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/blog/': typeof BlogIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agentic-experimental'
    | '/identus'
    | '/known-issues'
    | '/llms'
    | '/mobile'
    | '/proof-server'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/blog/$slug'
    | '/ideas/$id'
    | '/showcase/a2a-ap2-negotiation'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/showcase/ucp-zk-checkout'
    | '/showcase/x402-midnight-paywall'
    | '/themes/$theme'
    | '/blog/'
    | '/showcase/'
    | '/themes/'
    | '/api/public/x402-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agentic-experimental'
    | '/identus'
    | '/known-issues'
    | '/llms'
    | '/mobile'
    | '/proof-server'
    | '/quantum-primer'
    | '/strategy'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/blog/$slug'
    | '/ideas/$id'
    | '/showcase/a2a-ap2-negotiation'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/showcase/ucp-zk-checkout'
    | '/showcase/x402-midnight-paywall'
    | '/themes/$theme'
    | '/blog'
    | '/showcase'
    | '/themes'
    | '/api/public/x402-proxy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agentic-experimental'
    | '/identus'
    | '/known-issues'
    | '/llms'
    | '/mobile'
    | '/proof-server'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/blog/$slug'
    | '/ideas/$id'
    | '/showcase/a2a-ap2-negotiation'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/showcase/ucp-zk-checkout'
    | '/showcase/x402-midnight-paywall'
    | '/themes/$theme'
    | '/blog/'
    | '/showcase/'
    | '/themes/'
    | '/api/public/x402-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgenticExperimentalRoute: typeof AgenticExperimentalRoute
  IdentusRoute: typeof IdentusRoute
  KnownIssuesRoute: typeof KnownIssuesRoute
  LlmsRoute: typeof LlmsRoute
  MobileRoute: typeof MobileRoute
  ProofServerRoute: typeof ProofServerRoute
  QuantumPrimerRoute: typeof QuantumPrimerRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  StrategyRoute: typeof StrategyRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  UndeployedRoute: typeof UndeployedRoute
  UndeployedPreflightRoute: typeof UndeployedPreflightRoute
  WalletRoute: typeof WalletRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IdeasIdRoute: typeof IdeasIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicX402ProxyRoute: typeof ApiPublicX402ProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undeployed-preflight': {
      id: '/undeployed-preflight'
      path: '/undeployed-preflight'
      fullPath: '/undeployed-preflight'
      preLoaderRoute: typeof UndeployedPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undeployed': {
      id: '/undeployed'
      path: '/undeployed'
      fullPath: '/undeployed'
      preLoaderRoute: typeof UndeployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-primer': {
      id: '/quantum-primer'
      path: '/quantum-primer'
      fullPath: '/quantum-primer'
      preLoaderRoute: typeof QuantumPrimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-server': {
      id: '/proof-server'
      path: '/proof-server'
      fullPath: '/proof-server'
      preLoaderRoute: typeof ProofServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms': {
      id: '/llms'
      path: '/llms'
      fullPath: '/llms'
      preLoaderRoute: typeof LlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/known-issues': {
      id: '/known-issues'
      path: '/known-issues'
      fullPath: '/known-issues'
      preLoaderRoute: typeof KnownIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identus': {
      id: '/identus'
      path: '/identus'
      fullPath: '/identus'
      preLoaderRoute: typeof IdentusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-experimental': {
      id: '/agentic-experimental'
      path: '/agentic-experimental'
      fullPath: '/agentic-experimental'
      preLoaderRoute: typeof AgenticExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$theme': {
      id: '/themes/$theme'
      path: '/$theme'
      fullPath: '/themes/$theme'
      preLoaderRoute: typeof ThemesThemeRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/x402-midnight-paywall': {
      id: '/showcase/x402-midnight-paywall'
      path: '/x402-midnight-paywall'
      fullPath: '/showcase/x402-midnight-paywall'
      preLoaderRoute: typeof ShowcaseX402MidnightPaywallRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/ucp-zk-checkout': {
      id: '/showcase/ucp-zk-checkout'
      path: '/ucp-zk-checkout'
      fullPath: '/showcase/ucp-zk-checkout'
      preLoaderRoute: typeof ShowcaseUcpZkCheckoutRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/programmatic-dust': {
      id: '/showcase/programmatic-dust'
      path: '/programmatic-dust'
      fullPath: '/showcase/programmatic-dust'
      preLoaderRoute: typeof ShowcaseProgrammaticDustRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/move-board': {
      id: '/showcase/move-board'
      path: '/move-board'
      fullPath: '/showcase/move-board'
      preLoaderRoute: typeof ShowcaseMoveBoardRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/midnight-ledger': {
      id: '/showcase/midnight-ledger'
      path: '/midnight-ledger'
      fullPath: '/showcase/midnight-ledger'
      preLoaderRoute: typeof ShowcaseMidnightLedgerRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/choreo-ledger-local': {
      id: '/showcase/choreo-ledger-local'
      path: '/choreo-ledger-local'
      fullPath: '/showcase/choreo-ledger-local'
      preLoaderRoute: typeof ShowcaseChoreoLedgerLocalRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/a2a-ap2-negotiation': {
      id: '/showcase/a2a-ap2-negotiation'
      path: '/a2a-ap2-negotiation'
      fullPath: '/showcase/a2a-ap2-negotiation'
      preLoaderRoute: typeof ShowcaseA2aAp2NegotiationRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-proxy': {
      id: '/api/public/x402-proxy'
      path: '/api/public/x402-proxy'
      fullPath: '/api/public/x402-proxy'
      preLoaderRoute: typeof ApiPublicX402ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowcaseRouteChildren {
  ShowcaseA2aAp2NegotiationRoute: typeof ShowcaseA2aAp2NegotiationRoute
  ShowcaseChoreoLedgerLocalRoute: typeof ShowcaseChoreoLedgerLocalRoute
  ShowcaseMidnightLedgerRoute: typeof ShowcaseMidnightLedgerRoute
  ShowcaseMoveBoardRoute: typeof ShowcaseMoveBoardRoute
  ShowcaseProgrammaticDustRoute: typeof ShowcaseProgrammaticDustRoute
  ShowcaseUcpZkCheckoutRoute: typeof ShowcaseUcpZkCheckoutRoute
  ShowcaseX402MidnightPaywallRoute: typeof ShowcaseX402MidnightPaywallRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseA2aAp2NegotiationRoute: ShowcaseA2aAp2NegotiationRoute,
  ShowcaseChoreoLedgerLocalRoute: ShowcaseChoreoLedgerLocalRoute,
  ShowcaseMidnightLedgerRoute: ShowcaseMidnightLedgerRoute,
  ShowcaseMoveBoardRoute: ShowcaseMoveBoardRoute,
  ShowcaseProgrammaticDustRoute: ShowcaseProgrammaticDustRoute,
  ShowcaseUcpZkCheckoutRoute: ShowcaseUcpZkCheckoutRoute,
  ShowcaseX402MidnightPaywallRoute: ShowcaseX402MidnightPaywallRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface ThemesRouteChildren {
  ThemesThemeRoute: typeof ThemesThemeRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemeRoute: ThemesThemeRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgenticExperimentalRoute: AgenticExperimentalRoute,
  IdentusRoute: IdentusRoute,
  KnownIssuesRoute: KnownIssuesRoute,
  LlmsRoute: LlmsRoute,
  MobileRoute: MobileRoute,
  ProofServerRoute: ProofServerRoute,
  QuantumPrimerRoute: QuantumPrimerRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  StrategyRoute: StrategyRoute,
  ThemesRoute: ThemesRouteWithChildren,
  UndeployedRoute: UndeployedRoute,
  UndeployedPreflightRoute: UndeployedPreflightRoute,
  WalletRoute: WalletRoute,
  BlogSlugRoute: BlogSlugRoute,
  IdeasIdRoute: IdeasIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicX402ProxyRoute: ApiPublicX402ProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
