/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UndeployedPreflightRouteImport } from './routes/undeployed-preflight'
import { Route as UndeployedRouteImport } from './routes/undeployed'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as QuantumPrimerRouteImport } from './routes/quantum-primer'
import { Route as ProofServerRouteImport } from './routes/proof-server'
import { Route as LlmsRouteImport } from './routes/llms'
import { Route as KnownIssuesRouteImport } from './routes/known-issues'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as ThemesThemeRouteImport } from './routes/themes.$theme'
import { Route as ShowcaseProgrammaticDustRouteImport } from './routes/showcase.programmatic-dust'
import { Route as ShowcaseMoveBoardRouteImport } from './routes/showcase.move-board'
import { Route as ShowcaseMidnightLedgerRouteImport } from './routes/showcase.midnight-ledger'
import { Route as ShowcaseChoreoLedgerLocalRouteImport } from './routes/showcase.choreo-ledger-local'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UndeployedPreflightRoute = UndeployedPreflightRouteImport.update({
  id: '/undeployed-preflight',
  path: '/undeployed-preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const UndeployedRoute = UndeployedRouteImport.update({
  id: '/undeployed',
  path: '/undeployed',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumPrimerRoute = QuantumPrimerRouteImport.update({
  id: '/quantum-primer',
  path: '/quantum-primer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofServerRoute = ProofServerRouteImport.update({
  id: '/proof-server',
  path: '/proof-server',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsRoute = LlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const KnownIssuesRoute = KnownIssuesRouteImport.update({
  id: '/known-issues',
  path: '/known-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ThemesThemeRoute = ThemesThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseProgrammaticDustRoute =
  ShowcaseProgrammaticDustRouteImport.update({
    id: '/programmatic-dust',
    path: '/programmatic-dust',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const ShowcaseMoveBoardRoute = ShowcaseMoveBoardRouteImport.update({
  id: '/move-board',
  path: '/move-board',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseMidnightLedgerRoute = ShowcaseMidnightLedgerRouteImport.update({
  id: '/midnight-ledger',
  path: '/midnight-ledger',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseChoreoLedgerLocalRoute =
  ShowcaseChoreoLedgerLocalRouteImport.update({
    id: '/choreo-ledger-local',
    path: '/choreo-ledger-local',
    getParentRoute: () => ShowcaseRoute,
  } as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/strategy': typeof StrategyRoute
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/themes': typeof ThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/known-issues': typeof KnownIssuesRoute
  '/llms': typeof LlmsRoute
  '/proof-server': typeof ProofServerRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/undeployed': typeof UndeployedRoute
  '/undeployed-preflight': typeof UndeployedPreflightRoute
  '/wallet': typeof WalletRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/choreo-ledger-local': typeof ShowcaseChoreoLedgerLocalRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/showcase/move-board': typeof ShowcaseMoveBoardRoute
  '/showcase/programmatic-dust': typeof ShowcaseProgrammaticDustRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/known-issues'
    | '/llms'
    | '/proof-server'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/ideas/$id'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/themes/$theme'
    | '/showcase/'
    | '/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/known-issues'
    | '/llms'
    | '/proof-server'
    | '/quantum-primer'
    | '/strategy'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/ideas/$id'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/themes/$theme'
    | '/showcase'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/known-issues'
    | '/llms'
    | '/proof-server'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/undeployed'
    | '/undeployed-preflight'
    | '/wallet'
    | '/ideas/$id'
    | '/showcase/choreo-ledger-local'
    | '/showcase/midnight-ledger'
    | '/showcase/move-board'
    | '/showcase/programmatic-dust'
    | '/themes/$theme'
    | '/showcase/'
    | '/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  KnownIssuesRoute: typeof KnownIssuesRoute
  LlmsRoute: typeof LlmsRoute
  ProofServerRoute: typeof ProofServerRoute
  QuantumPrimerRoute: typeof QuantumPrimerRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  StrategyRoute: typeof StrategyRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  UndeployedRoute: typeof UndeployedRoute
  UndeployedPreflightRoute: typeof UndeployedPreflightRoute
  WalletRoute: typeof WalletRoute
  IdeasIdRoute: typeof IdeasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undeployed-preflight': {
      id: '/undeployed-preflight'
      path: '/undeployed-preflight'
      fullPath: '/undeployed-preflight'
      preLoaderRoute: typeof UndeployedPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undeployed': {
      id: '/undeployed'
      path: '/undeployed'
      fullPath: '/undeployed'
      preLoaderRoute: typeof UndeployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-primer': {
      id: '/quantum-primer'
      path: '/quantum-primer'
      fullPath: '/quantum-primer'
      preLoaderRoute: typeof QuantumPrimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-server': {
      id: '/proof-server'
      path: '/proof-server'
      fullPath: '/proof-server'
      preLoaderRoute: typeof ProofServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms': {
      id: '/llms'
      path: '/llms'
      fullPath: '/llms'
      preLoaderRoute: typeof LlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/known-issues': {
      id: '/known-issues'
      path: '/known-issues'
      fullPath: '/known-issues'
      preLoaderRoute: typeof KnownIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/themes/$theme': {
      id: '/themes/$theme'
      path: '/$theme'
      fullPath: '/themes/$theme'
      preLoaderRoute: typeof ThemesThemeRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/programmatic-dust': {
      id: '/showcase/programmatic-dust'
      path: '/programmatic-dust'
      fullPath: '/showcase/programmatic-dust'
      preLoaderRoute: typeof ShowcaseProgrammaticDustRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/move-board': {
      id: '/showcase/move-board'
      path: '/move-board'
      fullPath: '/showcase/move-board'
      preLoaderRoute: typeof ShowcaseMoveBoardRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/midnight-ledger': {
      id: '/showcase/midnight-ledger'
      path: '/midnight-ledger'
      fullPath: '/showcase/midnight-ledger'
      preLoaderRoute: typeof ShowcaseMidnightLedgerRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/choreo-ledger-local': {
      id: '/showcase/choreo-ledger-local'
      path: '/choreo-ledger-local'
      fullPath: '/showcase/choreo-ledger-local'
      preLoaderRoute: typeof ShowcaseChoreoLedgerLocalRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowcaseRouteChildren {
  ShowcaseChoreoLedgerLocalRoute: typeof ShowcaseChoreoLedgerLocalRoute
  ShowcaseMidnightLedgerRoute: typeof ShowcaseMidnightLedgerRoute
  ShowcaseMoveBoardRoute: typeof ShowcaseMoveBoardRoute
  ShowcaseProgrammaticDustRoute: typeof ShowcaseProgrammaticDustRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseChoreoLedgerLocalRoute: ShowcaseChoreoLedgerLocalRoute,
  ShowcaseMidnightLedgerRoute: ShowcaseMidnightLedgerRoute,
  ShowcaseMoveBoardRoute: ShowcaseMoveBoardRoute,
  ShowcaseProgrammaticDustRoute: ShowcaseProgrammaticDustRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface ThemesRouteChildren {
  ThemesThemeRoute: typeof ThemesThemeRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemeRoute: ThemesThemeRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  KnownIssuesRoute: KnownIssuesRoute,
  LlmsRoute: LlmsRoute,
  ProofServerRoute: ProofServerRoute,
  QuantumPrimerRoute: QuantumPrimerRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  StrategyRoute: StrategyRoute,
  ThemesRoute: ThemesRouteWithChildren,
  UndeployedRoute: UndeployedRoute,
  UndeployedPreflightRoute: UndeployedPreflightRoute,
  WalletRoute: WalletRoute,
  IdeasIdRoute: IdeasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
