/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as QuantumPrimerRouteImport } from './routes/quantum-primer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as ThemesThemeRouteImport } from './routes/themes.$theme'
import { Route as ShowcaseMidnightLedgerRouteImport } from './routes/showcase.midnight-ledger'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumPrimerRoute = QuantumPrimerRouteImport.update({
  id: '/quantum-primer',
  path: '/quantum-primer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ThemesThemeRoute = ThemesThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => ThemesRoute,
} as any)
const ShowcaseMidnightLedgerRoute = ShowcaseMidnightLedgerRouteImport.update({
  id: '/midnight-ledger',
  path: '/midnight-ledger',
  getParentRoute: () => ShowcaseRoute,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/strategy': typeof StrategyRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/themes': typeof ThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/ideas/$id': typeof IdeasIdRoute
  '/showcase/midnight-ledger': typeof ShowcaseMidnightLedgerRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/ideas/$id'
    | '/showcase/midnight-ledger'
    | '/themes/$theme'
    | '/showcase/'
    | '/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/quantum-primer'
    | '/strategy'
    | '/ideas/$id'
    | '/showcase/midnight-ledger'
    | '/themes/$theme'
    | '/showcase'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/ideas/$id'
    | '/showcase/midnight-ledger'
    | '/themes/$theme'
    | '/showcase/'
    | '/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  QuantumPrimerRoute: typeof QuantumPrimerRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  StrategyRoute: typeof StrategyRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  IdeasIdRoute: typeof IdeasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-primer': {
      id: '/quantum-primer'
      path: '/quantum-primer'
      fullPath: '/quantum-primer'
      preLoaderRoute: typeof QuantumPrimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/themes/$theme': {
      id: '/themes/$theme'
      path: '/$theme'
      fullPath: '/themes/$theme'
      preLoaderRoute: typeof ThemesThemeRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/showcase/midnight-ledger': {
      id: '/showcase/midnight-ledger'
      path: '/midnight-ledger'
      fullPath: '/showcase/midnight-ledger'
      preLoaderRoute: typeof ShowcaseMidnightLedgerRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowcaseRouteChildren {
  ShowcaseMidnightLedgerRoute: typeof ShowcaseMidnightLedgerRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseMidnightLedgerRoute: ShowcaseMidnightLedgerRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface ThemesRouteChildren {
  ThemesThemeRoute: typeof ThemesThemeRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemeRoute: ThemesThemeRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  QuantumPrimerRoute: QuantumPrimerRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  StrategyRoute: StrategyRoute,
  ThemesRoute: ThemesRouteWithChildren,
  IdeasIdRoute: IdeasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
